### ISSUE TITLE
brush up gurl client

### ISSUE THREAD

**Issue by sota0121** [sota0121/gurl#11]
## ToDo

- [x] Create ReqContext and CmdConfig structs
- [x] Create workflow to export ReqContext and CmdConfig instance from cmd.options
- [x] Remake directory structure with reference to [docker/compose](https://github.com/docker/compose)
- [x] Implement Simple Process - GET functionality
- [x] (Additional) Fix problem that shorthand option can't be recognized
    - `--request` works, but `-X` doesn't work.
- [ ] Implement GurlClient and Fix `CmdConfig` / `ReqContext` structs' attribute types (change dummy -> actual types). GurlClient request process is made from `net/http` pkg.
  - == Request Context ==
  - [ ] opt: request
  - [ ] opt: form
  - [ ] opt: data
  - opt: upload-file (not supported)
  - [ ] opt: user
  - [ ] opt: user-agent
  - == Command Configs ==
  - [x] opt: help
