### ISSUE TITLE
Design program architecture

### ISSUE THREAD

**Issue by sota0121** [sota0121/gurl#3]
## todo

- [ ] add directory of docs/drawio, docs/img, docs
- [ ] add design note as docs/ARCH.md or docs/drawio/ARCH.drawio
- [ ] create issues of development gURL command step by step
